//
// Created by arye on 20/01/2020.
//

#ifndef CLIENT_SERVER_COMMUNICATION__MATRIX_H_
#define CLIENT_SERVER_COMMUNICATION__MATRIX_H_

class Matrix {

};

#endif //CLIENT_SERVER_COMMUNICATION__MATRIX_H_
