//
// Created by miri on 23.1.2020.
//

#ifndef CLIENT_SERVER_COMMUNICATION__MYPARALLELSERVER_H_
#define CLIENT_SERVER_COMMUNICATION__MYPARALLELSERVER_H_

#endif //CLIENT_SERVER_COMMUNICATION__MYPARALLELSERVER_H_
