//
// Created by miri on 23.1.2020.
//

#ifndef CLIENT_SERVER_COMMUNICATION__SEARCHEROBJECTADAPTER_H_
#define CLIENT_SERVER_COMMUNICATION__SEARCHEROBJECTADAPTER_H_

class Searcher
#endif //CLIENT_SERVER_COMMUNICATION__SEARCHEROBJECTADAPTER_H_
